  backup/local-main-before-first-push[m
  chore/tenants-structure[m
  droid/bluebell-nav-pages[m
  feat/admin-integrations[m
  feat/bluebell-homepage-ui[m
  feat/category-image[m
  feat/p1.3b-plp-pdp[m
  feat/p1.3c-pdp[m
  feature/admin-dashboard-enhancement[m
  feature/bluebell-admin-enhancements[m
  feature/bluebell-tenant-agnostic-architecture[m
  feature/host-tenancy-bluebell-bridge[m
  feature/senlysh-frontend-enhancement[m
  feature/senlysh-public-nav-and-pages[m
  fix-critical-bugs[m
  fix-local-admin-auth[m
  fix-tenant-issues-critical[m
  fix/senlysh-data-integration[m
  guardrail-implementation[m
  main[m
  pr-5[m
* [32mproduction-frontend-fixes[m
  staging[m
  [31mremotes/origin/chore/tenants-structure[m
  [31mremotes/origin/droid/bluebell-nav-pages[m
  [31mremotes/origin/droid/ci-guards[m
  [31mremotes/origin/droid/e2e-smoke-tests[m
  [31mremotes/origin/feat/admin-integrations[m
  [31mremotes/origin/feat/bluebell-homepage-ui[m
  [31mremotes/origin/feat/category-image[m
  [31mremotes/origin/feat/p1.3b-plp-pdp[m
  [31mremotes/origin/feat/p1.3c-pdp[m
  [31mremotes/origin/feature/admin-dashboard-enhancement[m
  [31mremotes/origin/feature/bluebell-admin-enhancements[m
  [31mremotes/origin/feature/bluebell-tenant-agnostic-architecture[m
  [31mremotes/origin/feature/host-tenancy-bluebell-bridge[m
  [31mremotes/origin/feature/senlysh-frontend-enhancement[m
  [31mremotes/origin/feature/senlysh-public-nav-and-pages[m
  [31mremotes/origin/fix-critical-bugs[m
  [31mremotes/origin/fix/senlysh-data-integration[m
  [31mremotes/origin/main[m
  [31mremotes/origin/pr-5[m
  [31mremotes/origin/staging[m
