import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TenantProvider from '@/components/TenantProvider'
import { resolveTenantIdFromRequest, resolveTenantKeyFromId } from '@/server/tenant'
import { getHeaderComponent, getFooterComponent } from '@/tenants'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tenantId = await resolveTenantIdFromRequest()
  const tenantKey = tenantId ? await resolveTenantKeyFromId(tenantId) : 'default'
  const Header = getHeaderComponent(tenantKey || 'default')
  const Footer = getFooterComponent(tenantKey || 'default')
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* tenant shell */}
        <TenantProvider>
          <Header />
          {children}
          <Footer />
        </TenantProvider>
      </body>
    </html>
  );
}
