import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TenantProvider from '@/components/TenantProvider'
import { resolveTenantIdFromRequest } from '@/server/tenant'
import { supabaseAdmin, hasSupabaseEnv } from '@/server/supabaseAdmin'
import { getHeaderComponent, getFooterComponent } from '@/tenants'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tenantId = await resolveTenantIdFromRequest()
  let tenantKey = 'default'
  if (tenantId && hasSupabaseEnv && supabaseAdmin) {
    const { data: domain } = await supabaseAdmin
      .from('tenant_domains').select('hostname').eq('tenant_id', tenantId).eq('is_primary', true).maybeSingle()
    tenantKey = domain?.hostname?.split('.')[0] || 'default'
  }
  const Header = getHeaderComponent(tenantKey)
  const Footer = getFooterComponent(tenantKey)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* tenant shell */}
        <TenantProvider>
          <Header />
          {children}
          <Footer />
        </TenantProvider>
      </body>
    </html>
  );
}
