// Gadget Bazaar Configuration
// Generated by scaffold script on 2025-08-25

export const Gadget-bazaarConfig = {
  name: 'Gadget Bazaar',
  key: 'Gadget-bazaar',
  businessType: 'electronics',
  brand: {
    primaryColor: '',
    secondaryColor: '#64748b',
    accentColor: '#f59e0b',
  },
  features: {
    products: true,
    portfolio: true,
    blog: false,
    contact: true,
  },
  social: {
    facebook: 'https://facebook.com/Gadget-bazaar',
    instagram: 'https://instagram.com/Gadget-bazaar',
    twitter: 'https://twitter.com/Gadget-bazaar',
  },
  contact: {
    email: 'hello@Gadget-bazaar.com',
    phone: '(+91) 98765-43210',
    address: {
      street: '123 Business Street',
      city: 'New Delhi',
      state: 'Delhi',
      zipCode: '110001',
      country: 'India',
    },
  },
  seo: {
    title: 'Gadget Bazaar - Quality electronics Solutions',
    description: 'Discover premium electronics products at Gadget Bazaar. Quality, innovation, and customer satisfaction guaranteed.',
    keywords: 'electronics, quality, premium, Gadget-bazaar',
  },
}

export default Gadget-bazaarConfig
