#!/bin/bash
# Script to check and enable coupons module for Senlysh tenant

echo "🔍 Checking coupons module status for Senlysh..."
echo ""
echo "Step 1: Query your Supabase database:"
echo "1. Go to https://app.supabase.com -> Your Project -> SQL Editor"
echo "2. Run this query to CHECK the current status:"
echo ""
echo "------- QUERY TO CHECK STATUS -------"
echo "SELECT tenant_id, module_key, enabled FROM tenant_modules"
echo "WHERE module_key = 'coupons' AND tenant_id = '1e4c9aa7-e7af-4fe7-999b-c9c46219fa3c';"
echo "-------------------------------------"
echo ""
echo "If you get NO ROWS, the module needs to be created."
echo "If you get enabled = false, it needs to be enabled."
echo ""
echo "Step 2: To ENABLE the coupons module, run one of these:"
echo ""
echo "------- CREATE (if it doesn't exist) -------"
echo "INSERT INTO tenant_modules (tenant_id, module_key, enabled, config)"
echo "VALUES ("
echo "  '1e4c9aa7-e7af-4fe7-999b-c9c46219fa3c',"
echo "  'coupons',"
echo "  true,"
echo "  jsonb_build_object('features', array['create', 'edit', 'delete', 'manage'])"
echo ");"
echo "--------------------------------------------"
echo ""
echo "------- UPDATE (if it already exists but disabled) -------"
echo "UPDATE tenant_modules"
echo "SET enabled = true"
echo "WHERE tenant_id = '1e4c9aa7-e7af-4fe7-999b-c9c46219fa3c'"
echo "AND module_key = 'coupons';"
echo "--------------------------------------------"
echo ""
echo "Senlysh Tenant ID: 1e4c9aa7-e7af-4fe7-999b-c9c46219fa3c"
echo "Module Key: coupons"
